---
language: perl
perl:
- '5.14'
- '5.16'
- '5.18'
notifications:
  email: false
install:
- cpanm --notest Dist::Zilla
- dzil authordeps | cpanm --notest
- dzil listdeps | cpanm --notest
script:
- dzil test

