#!/usr/bin/env perl
# browse
# Quickly browse UA bugs via database
#
# Author: Adam Stokes <adam.stokes@ubuntu.com>

use strict;
use warnings;
use Net::OAuth::LP;
use File::Spec::Functions;
use Data::Dumper;

my $is_auth = 0;

if( -e catfile($ENV{HOME},'.lp-auth.yml' )) {
  $is_auth = 1;
}

my $lp = Net::OAuth::LP->new;
$lp->consumer_key('stokachu-wuz-here');

if ($is_auth == 0) {
  $lp->login_with_creds();
}

print Dumper($lp->call("~adam-stokes"));
print Dumper($lp->call("ubuntu-advantage"));
